# obstacle_range: 100.0 #设置机器人检测障碍物的最大距离
# raytrace_range: 100.0 #设置机器人检测自由空间的最大范围

# # footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
# robot_radius: 0.6 #机器人半径

# inflation_radius: 1.0 #这个参数表示机器人路径规划应与机器人保持0.1m以上的安全距离
# cost_scaling_factor: 3.0

# # max_obstacle_height: 1.0  #这两个参数用于描述障碍物的最大高度和最小高度
# # min_obstacle_height: 0.1
# map_type: costmap
# observation_sources: scan
# scan: {sensor_frame: rslidar, data_type: PointCloud2, topic: rslidar_points, marking: true, clearing: true}

robot_radius: 0.6

# obstacle_layer:
#   enabled: true
#   combination_method: 1 # 只能设置为0或1，用来更新地图上的代价值，一般设置为1
#   track_unknown_space: true # true时禁止探索未知区域
#   obstacle_range: 50.0 # 设置机器人检测障碍物的最大范围
#   raytrace_range: 60.0 # 在机器人移动过程中，实时清除代价地图上的障碍物的最大范围
#   observation_sources: scan
#   scan: {sensor_frame: rslidar, data_type: PointCloud2, topic: rslidar_points, marking: true, clearing: true}

inflation_layer:
  enabled: true
  cost_scaling_factor: 5.0
  inflation_radius: 1.5

static_layer:
  enabled: true