#footprint: [[0.6, 0.6], [0.6, -0.6], [-0.6, -0.6], [-0.6, -0.6]]  #尺寸
# map_type: costmap
# robot_radius: 0.5

# obstacle_layer:
#   enabled:              true
#   max_obstacle_height:  0.6
#   origin_z:             0.0
#   z_resolution:         0.2
#   z_voxels:             5
#   unknown_threshold:    15
#   mark_threshold:       0
#   combination_method:   1
#   track_unknown_space:  true
#   obstacle_range: 2.5
#   raytrace_range: 3.0
#   publish_voxel_map: false
#   observation_sources:  scan
#   scan:
#     {
#       frame_name: laser,
#       data_type: LaserScan,
#       topic: /scan,
#       inf_is_valid: true,
#       marking: true,
#       clearing: true,
#       min_obstacle_height: 0.0,
#       max_obstacle_height: 0.5}
#   # for debugging only, let's you see the entire voxel grid

# inflation_layer:
#   enabled:              true
#   cost_scaling_factor:  5.0
#   inflation_radius:     2.0

# static_layer:
#   enabled:              true

obstacle_range: 3.0
raytrace_range: 3.5

# footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
robot_radius: 0.6

inflation_radius: 1.0
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}