# global_costmap:
#   global_frame: map
#   robot_base_frame: base_link

#   update_frequency: 2.0
#   publish_frequency: 10.0
#   transform_tolerance: 0.5
#   track_unknown_space: true
#   rolling_window: true

#   static_map: true


global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 0.5
  static_map: true
  rolling_window: false
  transform_tolerance: 1.DS0
  plugins:
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    # - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
 