# shutdown_costmaps: false

# controller_frequency: 10.0
# controller_patience: 15.0 #1.0

# planner_frequency: 5.0 #10.0 l 
# max_planning_retries: 1 #l
# planner_patience: 5.0

# oscillation_timeout: 10.0
# oscillation_distance: 0.001

# # default: trajectory rollout
# base_local_planner: "dwa_local_planner/DWAPlannerROS"

# # navfn/NavfnROS、global_planner/GlobalPlanner、carrot_planner/CarrotPlanner三种；
# base_global_planner: "navfn/NavfnROS"

# recovery_behavior_enabled: false
# recovery_behaviors: [{"name":"super_conservative_reset1", "type":"clear_costmap_recovery/ClearCostmapRecovery"}]
# reset_distance: 5.0

shutdown_costmaps: false
controller_frequency: 10.0
planner_patience: 0.01 #5.0
controller_patience: 15.0
conservative_reset_dist: 3.0
planner_frequency: 5.0 # 0.0发两次路径
oscillation_timeout: 10.0
oscillation_distance: 0.001
recovery_behavior_enabled: false # 禁止恢复行为